import { LoadingSkeleton } from "@/components/dashboard/LoadingSkeleton";
import type { Analytics, Overview } from "@/components/dashboard/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { AlertCircle, ArrowRight, Info, Radio, Waves } from "lucide-react";
import { Link } from "react-router-dom";

function formatLatency(value: number | null | undefined) { return value == null ? "Not measured" : value >= 1000 ? `${(value / 1000).toFixed(2)} s` : `${Math.round(value)} ms`; }
function formatRate(value: number | null | undefined) { return value == null ? "Not measured" : `${Math.round(value * 100)}%`; }
function formatCost(value: number | null | undefined) { return value == null ? "Unknown" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", minimumFractionDigits: 4, maximumFractionDigits: 6 }).format(value / 1_000_000); }
function Coverage({ observed, total, noun = "sessions" }: { observed: number; total: number; noun?: string }) { return <span>{observed} of {total} {noun} measured</span>; }

function MetricCard({ label, value, coverage, detail }: { label: string; value: string; coverage: React.ReactNode; detail: string }) {
  return <Card className="min-w-0 rounded-xl shadow-none"><CardContent className="flex min-h-32 flex-col gap-2 p-4"><div className="flex items-center gap-1 text-xs font-medium text-muted-foreground">{label}<Tooltip><TooltipTrigger aria-label={`About ${label}`} className="rounded-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"><Info className="size-3.5" /></TooltipTrigger><TooltipContent sideOffset={6}>{detail}</TooltipContent></Tooltip></div><strong className="text-xl font-semibold tracking-tight text-foreground">{value}</strong><span className="mt-auto text-xs text-muted-foreground">{coverage}</span></CardContent></Card>;
}

export function OverviewPanel({ overview, analytics, findingsCount, loading, environments, environmentFilter, startedAfter, startedBefore, onEnvironmentChange, onStartedAfterChange, onStartedBeforeChange, onClearFilters }: { overview: Overview | null; analytics: Analytics | null; findingsCount: number; loading: boolean; environments: Array<{ name: string; slug: string }>; environmentFilter: string; startedAfter: string; startedBefore: string; onEnvironmentChange(value: string): void; onStartedAfterChange(value: string): void; onStartedBeforeChange(value: string): void; onClearFilters(): void; }) {
  if (loading) return <LoadingSkeleton rows={8} />;
  const total = analytics?.session_count ?? 0;
  const coverage = analytics?.metric_coverage;
  const needsReview = (analytics?.rates.error ?? 0) > 0 || (analytics?.rates.abandonment ?? 0) > 0;
  return <TooltipProvider><div className="flex flex-col gap-6">
    <Card className="rounded-xl shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)_auto] md:items-end">
      <label className="flex flex-col gap-1.5 text-xs font-medium text-muted-foreground">Environment<NativeSelect value={environmentFilter} onChange={(event) => onEnvironmentChange(event.target.value)}><option value="">All environments</option>{environments.map((item) => <option value={item.slug} key={item.slug}>{item.name}</option>)}</NativeSelect></label>
      <label className="flex flex-col gap-1.5 text-xs font-medium text-muted-foreground">Started after<Input type="date" value={startedAfter} onChange={(event) => onStartedAfterChange(event.target.value)} /></label>
      <label className="flex flex-col gap-1.5 text-xs font-medium text-muted-foreground">Started before<Input type="date" value={startedBefore} onChange={(event) => onStartedBeforeChange(event.target.value)} /></label>
      <Button variant="outline" disabled={!environmentFilter && !startedAfter && !startedBefore} onClick={onClearFilters}>Clear filters</Button>
    </CardContent></Card>
    {!total ? <EmptyWorkspace /> : <>
      <section className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(30rem,1fr)]" aria-label="Operator summary">
        <Card className="border-primary/20 bg-primary text-primary-foreground shadow-none"><CardContent className="flex h-full flex-col gap-7 p-6 sm:p-8"><Badge variant="secondary" className="w-fit gap-1.5 bg-background/15 text-primary-foreground hover:bg-background/15">{needsReview ? <AlertCircle className="size-3.5" /> : <Radio className="size-3.5" />}{needsReview ? "Calls need review" : "Telemetry is live"}</Badge><div className="max-w-xl"><p className="text-sm text-primary-foreground/70">Voice operations</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{analytics?.rates.resolution == null ? "Outcome coverage is still building." : `${formatRate(analytics.rates.resolution)} of measured outcomes resolved.`}</h2><p className="mt-3 text-sm leading-6 text-primary-foreground/75">Start with data quality, then move directly into the sessions that explain the result.</p></div><div className="flex flex-wrap gap-2 text-xs text-primary-foreground/80"><span className="rounded-full bg-background/10 px-3 py-1.5"><Coverage {...(coverage?.outcomes ?? { observed: 0, total })} noun="outcomes" /></span><span className="rounded-full bg-background/10 px-3 py-1.5">{findingsCount} evidence-linked findings</span></div></CardContent></Card>
        <div className="grid grid-cols-2 gap-3"><MetricCard label="Calls observed" value={total.toLocaleString()} coverage={`${analytics?.completed_session_count ?? 0} terminal sessions`} detail="Calls with at least one telemetry event in the selected period." /><MetricCard label="Resolution" value={formatRate(analytics?.rates.resolution)} coverage={<Coverage {...(coverage?.outcomes ?? { observed: 0, total })} noun="outcomes" />} detail="Resolved outcomes divided by sessions with a known outcome." /><MetricCard label="STT p90" value={formatLatency(analytics?.latency.stt?.p90_ms)} coverage={<Coverage {...(coverage?.stt_latency ?? { observed: 0, total })} />} detail="90th percentile of recorded speech-to-text spans. It is never shown as zero when spans are absent." /><MetricCard label="Human escalation" value={formatRate(analytics?.rates.escalation)} coverage={<Coverage {...(coverage?.escalations ?? { observed: 0, total })} noun="escalations" />} detail="Only terminal outcomes explicitly marked escalated. Automated agent handoffs are separate." /></div>
      </section>
      <Card className="border-amber-200 bg-amber-50/60 shadow-none"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><Waves className="mt-0.5 size-5 text-amber-700" /><div><p className="font-medium text-foreground">Data confidence</p><p className="text-sm text-muted-foreground">Comparisons need five measured outcomes per group to avoid presenting random variation as a trend. Per-session evidence is always available.</p></div></div><Button asChild variant="outline" size="sm"><Link to="/sessions">Review sessions <ArrowRight data-icon="inline-end" /></Link></Button></CardContent></Card>
      <section className="grid gap-4 xl:grid-cols-2" aria-label="Resolution analysis"><IntentResolution intents={analytics?.intent_comparisons ?? []} /><InterruptionResolution points={analytics?.interruption_resolution_points ?? []} /></section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Trace signal coverage"><MetricCard label="Caller corrections" value={formatRate(analytics?.rates.correction)} coverage={`${analytics?.voice_behavior.correction_sessions ?? 0} explicit correction events`} detail="Corrections are counted only from explicit adapter events, never inferred from silence." /><MetricCard label="Automated handoffs" value={formatRate(analytics?.rates.handoff)} coverage={`${analytics?.voice_behavior.handoff_sessions ?? 0} session events`} detail="Agent-to-agent transfers are operational handoffs, not human escalations." /><MetricCard label="Interrupted calls" value={`${analytics?.voice_behavior.interruption_sessions ?? 0}`} coverage={`${analytics?.voice_behavior.talk_over_sessions ?? 0} talk-over signals`} detail="A call is counted once when at least one interruption event was recorded." /><MetricCard label="Dead-air calls" value={`${analytics?.voice_behavior.dead_air_sessions ?? 0}`} coverage="Event or measured turn gap" detail="Dead air is detected from explicit events or a measured gap between turns." /></section>
      <section className="grid gap-4 xl:grid-cols-2" aria-label="Investigation queues"><InvestigationQueue title="Needs investigation" items={(analytics?.insights ?? []).filter((item) => item.count > 0)} empty="No recurring issues are currently recorded." /><InvestigationQueue title="Agent and provider evidence" items={comparisonItems(analytics)} empty="Comparisons appear once agents or providers report outcomes." /></section>
      <Card className="shadow-none"><CardHeader><h2 className="text-base font-semibold">Cost and voice usage</h2></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">Tracked cost</p><p className="mt-1 font-semibold">{formatCost(analytics?.cost.amount_micros)}</p></div><div><p className="text-muted-foreground">Voice usage</p><p className="mt-1 font-semibold">{analytics?.usage.audio_seconds == null ? "Not reported" : `${analytics.usage.audio_seconds.toFixed(1)} seconds`}</p></div><div><p className="text-muted-foreground">Active sessions</p><p className="mt-1 font-semibold">{overview?.metrics.active_sessions ?? 0}</p></div></CardContent></Card>
    </>}
  </div></TooltipProvider>;
}

function EmptyWorkspace() { return <Card className="shadow-none"><CardContent className="p-8"><h2 className="text-lg font-semibold">Your workspace is ready for its first call</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">No conversation evidence has arrived yet. Connect an agent, make a call, and the dashboard will show coverage before it shows performance.</p><Button asChild className="mt-5"><Link to="/setup">Connect an agent</Link></Button></CardContent></Card>; }

function IntentResolution({ intents }: { intents: Analytics["intent_comparisons"] }) { const data = intents.filter((item) => item.resolution_rate != null).sort((a, b) => b.sessions - a.sessions).slice(0, 4); return <Card className="shadow-none"><CardHeader><h2 className="text-base font-semibold">Intent resolution</h2><p className="text-sm text-muted-foreground">Controlled routing categories only; raw model text stays in the trace.</p></CardHeader><CardContent className="flex flex-col gap-4">{data.length ? data.map((item) => <div key={item.label} className="flex flex-col gap-2"><div className="flex items-center justify-between gap-3"><span className="truncate text-sm font-medium">{item.label}</span><span className="shrink-0 text-sm tabular-nums text-muted-foreground">{formatRate(item.resolution_rate)} · {item.known_outcomes}/{item.sessions}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.round((item.resolution_rate ?? 0) * 100)}%` }} /></div>{item.session_ids[0] ? <Link className="w-fit text-xs font-medium text-primary underline-offset-4 hover:underline" to={`/sessions/${item.session_ids[0]}`}>Open supporting session</Link> : null}</div>) : <p className="text-sm text-muted-foreground">No known outcomes have been paired with an intent yet.</p>}</CardContent></Card>; }

function InterruptionResolution({ points }: { points: Analytics["interruption_resolution_points"] }) { const groups = [{ label: "No interruptions", test: (value: number) => value === 0 }, { label: "One interruption", test: (value: number) => value === 1 }, { label: "Two or more", test: (value: number) => value >= 2 }].map((group) => { const rows = points.filter((point) => group.test(point.interruptions)); return { ...group, total: rows.length, resolved: rows.filter((point) => point.resolution === 1).length, sample: rows[0] }; }).filter((group) => group.total > 0); return <Card className="shadow-none"><CardHeader><h2 className="text-base font-semibold">Interruption impact</h2><p className="text-sm text-muted-foreground">Resolution by call-quality bucket replaces the ambiguous binary scatter plot.</p></CardHeader><CardContent className="flex flex-col gap-4">{groups.length ? groups.map((group) => { const rate = group.resolved / group.total; return <div key={group.label} className="rounded-lg border bg-card p-3"><div className="flex justify-between gap-3"><span className="text-sm font-medium">{group.label}</span><span className="text-sm tabular-nums">{formatRate(rate)}</span></div><p className="mt-1 text-xs text-muted-foreground">{group.resolved} resolved of {group.total} measured outcomes</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-chart-2" style={{ width: `${Math.round(rate * 100)}%` }} /></div>{group.sample ? <Link className="mt-3 inline-block text-xs font-medium text-primary underline-offset-4 hover:underline" to={`/sessions/${group.sample.session_id}`}>Open an example</Link> : null}</div>; }) : <p className="text-sm text-muted-foreground">Interruption comparisons appear after calls have known outcomes.</p>}</CardContent></Card>; }

function InvestigationQueue({ title, items, empty }: { title: string; items: Array<{ label: string; count: number; session_ids: string[] }>; empty: string }) { return <Card className="shadow-none"><CardHeader><h2 className="text-base font-semibold">{title}</h2></CardHeader><CardContent>{items.length ? <div className="flex flex-col divide-y">{items.slice(0, 8).map((item) => <div className="flex items-center justify-between gap-4 py-3" key={item.label}><span className="min-w-0 truncate text-sm">{item.label}</span>{item.session_ids[0] ? <Button asChild variant="ghost" size="sm"><Link to={`/sessions/${item.session_ids[0]}`}>{item.count} <ArrowRight data-icon="inline-end" /></Link></Button> : <Badge variant="secondary">{item.count}</Badge>}</div>)}</div> : <p className="text-sm text-muted-foreground">{empty}</p>}</CardContent></Card>; }

function comparisonItems(analytics: Analytics | null): Array<{ label: string; count: number; session_ids: string[] }> { if (!analytics) return []; return Object.entries(analytics.comparisons).flatMap(([kind, items]) => items.filter((item) => item.known_outcomes > 0).map((item) => ({ label: `${kind.slice(0, -1)} · ${item.label} · ${formatRate(item.resolution_rate)}`, count: item.sessions, session_ids: item.session_ids }))).slice(0, 8); }
