"""support external trace identifiers

Revision ID: b0271231ca60
Revises: a7db97a8e924
Create Date: 2026-09-20 18:42:51.969289

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b0271231ca60"
down_revision: str | Sequence[str] | None = "a7db97a8e924"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("external_run_id", sa.String(length=64), nullable=False))
    op.create_unique_constraint(
        "uq_agent_run_session_external", "agent_runs", ["session_id", "external_run_id"]
    )
    op.add_column(
        "spans", sa.Column("parent_external_span_id", sa.String(length=64), nullable=True)
    )
    op.add_column("turns", sa.Column("external_turn_id", sa.String(length=64), nullable=False))
    op.create_unique_constraint(
        "uq_turn_session_external", "turns", ["session_id", "external_turn_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_turn_session_external", "turns", type_="unique")
    op.drop_column("turns", "external_turn_id")
    op.drop_column("spans", "parent_external_span_id")
    op.drop_constraint("uq_agent_run_session_external", "agent_runs", type_="unique")
    op.drop_column("agent_runs", "external_run_id")
    # ### end Alembic commands ###
